version: "3.8"

services:
    mysql:
      image: mysql:8.0.29
      ports:
        - "3306:3306"
      networks:
        - shock-shack
      deploy:
        resources:
          limits:
            memory: 700m
      environment:
        MYSQL_ROOT_PASSWORD: "dnekdxkdxkd"
        MYSQL_DATABASE: chat
        MYSQL_USER: ymc
        MYSQL_PASSWORD: dnekdxkdxkd

    doodle:
      image: ruldarm00/shock-shack
      ports:
        - "8080:8080"
      networks:
        - shock-shack
      deploy:
        resources:
          limits:
            memory: 700m
        restart_policy:
          condition: on-failure
          delay: 30s
          max_attempts: 3
          window: 120s
      depends_on:
        - mysql

networks:
  shock-shack: